/* This file is generated by scripts/generate_frontend_contracts.py. */
/* Do not edit by hand; run `make frontend-contracts`. */

export const CONTRACT_SOURCE_SHA256 = "6d08feb00ea24e9ff666c13133a32b529eedc9e00352bf672212a16ead0b6496" as const;

export type ContractMainTask = {
  schema_version: "1.0";
  task_id: string;
  title: string;
  goal: string;
  master_owner: string;
  start_policy: "manual" | "auto";
  status: "DRAFT" | "PLANNED" | "AWAITING_START_CONFIRMATION" | "RUNNING" | "WAITING_APPROVAL" | "BLOCKED_UNAVAILABLE" | "FAILED" | "SUCCEEDED" | "PARTIAL" | "CANCELLED";
  created_at: string;
  updated_at: string;
  input_manifest: string;
  plan_revision: number;
};

export type ContractStage = {
  schema_version: "1.0";
  stage_id: string;
  task_id: string;
  type: "image" | "ppt";
  position: number;
  depends_on: string[];
  required: boolean;
  requirement_lifecycle: {
  original_required: boolean;
  first_activated_at: null | string;
  authorized_downgrade: null | {
  authorization_id: string;
  authorized_at: string;
  authorized_by_type: "human" | "master";
  authorized_by_id: string;
  plan_revision: number;
  reason: string;
};
} & ({
  original_required?: false;
  authorized_downgrade?: null;
} | {
  original_required?: true;
  authorized_downgrade?: null;
} | {
  original_required?: true;
  first_activated_at?: string;
  authorized_downgrade?: {
  authorization_id: string;
  authorized_at: string;
  authorized_by_type: "human" | "master";
  authorized_by_id: string;
  plan_revision: number;
  reason: string;
};
});
  status: "PENDING" | "READY" | "RUNNING" | "WAITING_APPROVAL" | "SUCCEEDED" | "FAILED" | "UNAVAILABLE" | "SKIPPED" | "CANCELLED";
  instance_ids: string[];
};

export type ContractWorkItem = {
  schema_version: "1.0";
  work_item_id: string;
  task_id: string;
  stage_id: string;
  title: string;
  agent_type: "image" | "ppt";
  required: boolean;
  depends_on: string[];
  current_instance_id: null | string;
  instance_ids: string[];
  task_card_ids: string[];
};

export type ContractWorkItemProjection = {
  schema_version: "1.0";
  work_item_id: string;
  task_id: string;
  title: string;
  agent_type: "image" | "ppt";
  required: boolean;
  depends_on: string[];
  stage: {
  stage_id: string;
  position: number;
  type: "image" | "ppt";
  status: string;
  depends_on: string[];
  available: boolean;
};
  business_status: "TODO" | "RUNNING" | "WAITING_APPROVAL" | "COMPLETED" | "EXCEPTION";
  raw_status: string;
  current_instance: null | {
  instance_id: string;
  status: string;
  approval_mode: "human" | "master";
  process_state: string | null;
  restart_required: boolean;
  created_at: string;
};
  instance_ids: string[];
  attempts: ({
  attempt_id: string;
  instance_id: string;
  status: string;
  automatic: boolean;
  created_at: string;
  settled_at: string | null;
})[];
  pending_approvals: ({
  approval_id: string;
  kind: "WORKFLOW" | "BUDGET_OVERRIDE" | "ASSET_DELETION";
  owner: "human" | "master";
  created_at: string;
})[];
  delivery_count: number;
  alerts: ({
  code: string;
  severity: "info" | "warning" | "error";
  message: string;
})[];
  updated_at: string;
};

export type ContractTaskIntake = {
  schema_version: "1.0";
  task_id: string;
  prompt: string;
  upload_session: {
  session_id: string;
  status: "OPEN" | "LOCKED" | "CANCELLED";
  accepted_mime_types: ("image/jpeg" | "image/png" | "image/webp" | "application/pdf" | "text/plain" | "text/markdown")[];
  max_files: number;
  max_total_bytes: number;
};
  asset_ids: string[];
  status: "DRAFT" | "SUBMITTED" | "CANCELLED";
  start_policy: "manual" | "auto";
  revision: number;
  created_at: string;
  updated_at: string;
  submitted_at: null | string;
} & ({
  status?: "DRAFT";
  submitted_at?: null;
  upload_session?: {
  status?: "OPEN";
};
} | {
  status?: "SUBMITTED";
  submitted_at?: string;
  upload_session?: {
  status?: "LOCKED";
};
} | {
  status?: "CANCELLED";
  submitted_at?: null;
  upload_session?: {
  status?: "CANCELLED";
};
});

export type ContractMasterMessage = {
  schema_version: "1.0";
  message_id: string;
  task_id: string;
  sequence: number;
  role: "user" | "master" | "system";
  kind: "text" | "clarification" | "plan_proposal" | "plan_confirmation" | "error";
  content: string;
  asset_refs: {
  asset_id: string;
  manifest_relpath: string;
}[];
  created_at: string;
};

export type ContractMasterThread = {
  schema_version: "1.0";
  task_id: string;
  latest_sequence: number;
  latest_proposal_revision: number;
  active_run: null | {
  run_id: null | string;
  message_id: string;
  status: "SUBMITTING" | "RUNNING" | "NEEDS_INPUT" | "PLAN_READY" | "FAILED";
  started_at: string;
  updated_at: string;
};
  last_error: null | {
  code: string;
  message: string;
  occurred_at: string;
};
  revision: number;
  created_at: string;
  updated_at: string;
};

export type ContractPlanProposal = {
  schema_version: "1.0";
  proposal_id: string;
  task_id: string;
  revision: number;
  status: "PENDING_CONFIRMATION" | "CONFIRMED" | "SUPERSEDED" | "REJECTED";
  stages: ({
  stage_id: string;
  type: "image" | "ppt";
  position: number;
  depends_on: string[];
  required: boolean;
})[];
  work_items: ({
  schema_version: "1.0";
  work_item_id: string;
  task_id: string;
  stage_id: string;
  title: string;
  agent_type: "image" | "ppt";
  required: boolean;
  depends_on: string[];
  current_instance_id: null | string;
  instance_ids: string[];
  task_card_ids: string[];
})[];
  execution_cards: ({
  schema_version: "1.1";
  card_id: string;
  revision: number;
  task_id: string;
  stage_id: string;
  instance_id: string;
  agent_type: "image" | "ppt";
  objective: string;
  instructions: string[];
  input_assets: {
  asset_id: string;
  manifest_relpath: string;
}[];
  expected_deliveries: ({
  kind: "image" | "presentation" | "document" | "archive" | "other";
  role: string;
  required: boolean;
  accepted_mime_types: string[];
})[];
  parameters: Record<string, unknown>;
  retry_group_id?: string;
  created_at: string;
} & ({
  agent_type?: "image";
  parameters?: {
  aspect_ratio?: string;
  variants?: number;
  usage_context?: string;
  category_id?: string;
  category_version?: string;
};
} | {
  agent_type?: "ppt";
  parameters?: {
  slide_count?: number;
  planned_asset_role?: string;
};
}))[];
  created_at: string;
  updated_at: string;
  confirmed_at: null | string;
};

export type ContractTaskNavigationMetadata = {
  schema_version: "1.0";
  task_id: string;
  pinned_at: null | string;
  archived_at: null | string;
  display_order: number;
  revision: number;
  updated_at: string;
} & ({
  archived_at?: null;
} | {
  archived_at?: string;
  pinned_at?: null;
});

export type ContractAgentInstance = {
  schema_version: "1.0";
  instance_id: string;
  task_id: string;
  stage_id: string;
  agent_type: "image" | "ppt";
  required: boolean;
  requirement_lifecycle: {
  original_required: boolean;
  first_activated_at: null | string;
  authorized_downgrade: null | {
  authorization_id: string;
  authorized_at: string;
  authorized_by_type: "human" | "master";
  authorized_by_id: string;
  plan_revision: number;
  reason: string;
};
} & ({
  original_required?: false;
  authorized_downgrade?: null;
} | {
  original_required?: true;
  authorized_downgrade?: null;
} | {
  original_required?: true;
  first_activated_at?: string;
  authorized_downgrade?: {
  authorization_id: string;
  authorized_at: string;
  authorized_by_type: "human" | "master";
  authorized_by_id: string;
  plan_revision: number;
  reason: string;
};
});
  status: "CREATED" | "READY" | "UNAVAILABLE" | "STARTING" | "RUNNING" | "WAITING_APPROVAL" | "FAILED_TO_START" | "SUCCEEDED" | "FAILED" | "CRASHED" | "CANCELLED" | "SUPERSEDED" | "ARCHIVED";
  approval_mode: "human" | "master";
  config_revision: number;
  credential_pair_ref: string;
  credential_pair_revision: number;
  workspace_relpath: string;
  task_card_relpath: string;
  ui_url: string | null;
  process: null | {
  pid: number;
  port: number;
  launch_id: string;
  state: "STARTING" | "RUNNING" | "EXITED";
  started_at: string;
};
  restart_required?: boolean;
  delivery_rejection?: null | {
  code: string;
  message: string;
  details: Record<string, unknown>;
  rejected_at: string;
  retryable: boolean;
};
  created_at: string;
};

export type ContractApprovalRequest = {
  schema_version: "1.0";
  approval_id: string;
  task_id: string;
  instance_id: string;
  step_id: string;
  kind: "WORKFLOW" | "BUDGET_OVERRIDE" | "ASSET_DELETION";
  owner: "human" | "master";
  status: "PENDING" | "APPROVED" | "REJECTED" | "CANCELLED";
  payload_ref: string;
  created_at: string;
  sequence: number;
  revision: number;
  resolved_at?: string;
  resolved_by_type?: "human" | "master" | "system" | "adapter";
  resolved_by_id?: string;
};

export type ContractDelivery = {
  schema_version: "1.0";
  delivery_id: string;
  task_id: string;
  stage_id: string;
  instance_id: string;
  task_card_id: string;
  task_card_revision: number;
  status: "CANDIDATE" | "PUBLISHED" | "REJECTED" | "CORRUPTED";
  outputs: ({
  source_relative_path: string;
  kind: "image" | "presentation" | "document" | "archive" | "other";
  role: string;
  description?: string;
})[];
  published_assets: {
  asset_id: string;
  manifest_relpath: string;
}[];
  created_at: string;
};

export type ContractDeliveryBundleCandidate = {
  schema_version: "1.0";
  bundle_id: string;
  task_id: string;
  work_item_id: string;
  instance_id: string;
  task_card_revision: number;
  branch_id: string;
  checkpoint_id: string;
  image: {
  private_relative_path: string;
  mime_type: "image/jpeg" | "image/png" | "image/webp";
  size_bytes: number;
  sha256: string;
  width: number;
  height: number;
};
  design_note: {
  private_relative_path: string;
  mime_type: "text/markdown";
  size_bytes: number;
  sha256: string;
};
  status: "PENDING_CONFIRMATION" | "PUBLISHED" | "REJECTED" | "CORRUPTED";
  created_at: string;
  decided_at: null | string;
  actor: null | {
  type: "human" | "master" | "system" | "adapter";
  id: string;
};
  publication_batch_id: null | string;
};

export type ContractBundleManifest = {
  schema_version: "1.0";
  bundle_id: string;
  task_id: string;
  work_item_id: string;
  instance_id: string;
  task_card_revision: number;
  branch_id: string;
  checkpoint_id: string;
  publication_batch_id: string;
  image_asset: {
  asset_id: string;
  manifest_relpath: string;
};
  design_note_asset: {
  asset_id: string;
  manifest_relpath: string;
};
  actor: {
  type: "human" | "master" | "system" | "adapter";
  id: string;
};
  created_at: string;
  published_at: string;
};

export type ContractAssetManifest = {
  schema_version: "1.0";
  asset_id: string;
  task_id: string;
  producer_instance_id: string | null;
  kind: "image" | "presentation" | "document" | "archive" | "other";
  role: string;
  relative_path: string;
  mime_type: string;
  size_bytes: number;
  sha256: string;
  description: string;
  derivation?: null | {
  source_sha256: string;
  source_mime_type: string;
  derived_sha256: string;
  derived_mime_type: string;
  transform: "jpeg_to_png";
  parameters: {
  format: "PNG";
  color_mode: "RGB" | "RGBA";
  compress_level: number;
  optimize: boolean;
};
};
  source_relative_path?: string;
  publication_id?: string;
  published_at?: string;
  created_at: string;
};

export type ContractInboxItem = {
  schema_version: "1.0";
  inbox_id: string;
  task_id: string;
  instance_id: string | null;
  approval_id: string | null;
  kind: "APPROVAL_REQUIRED" | "INSTANCE_SUCCEEDED" | "INSTANCE_FAILED" | "INSTANCE_DELIVERY_REJECTED" | "INSTANCE_CRASHED" | "TASK_SUCCEEDED" | "TASK_FAILED" | "STAGE_READY" | "CONFIG_RESTART_REQUIRED" | "BUDGET_APPROVAL_REQUIRED";
  owner: "human" | "master";
  status: "UNREAD" | "READ" | "HANDLED";
  title: string;
  message: string;
  deep_link: string;
  created_at: string;
  sequence: number;
  revision: number;
  dedupe_key: string;
  read_at?: string;
  read_by_type?: "human" | "master" | "system" | "adapter";
  read_by_id?: string;
  handled_at?: string;
  handled_by_type?: "human" | "master" | "system" | "adapter";
  handled_by_id?: string;
};

export type ContractTokenUsageEvent = {
  schema_version: "1.1";
  event_id: string;
  task_id: string;
  instance_id: string;
  agent_type: "image" | "ppt" | "master";
  request_id: string;
  provider_request_id: string | null;
  provider: string;
  model: string;
  call_type: "reasoning_llm" | "vision_language_model" | "text_to_image_model";
  usage_basis: "tokens" | "image_units" | "mixed";
  credential_pair_ref: string | null;
  input_tokens: number;
  output_tokens: number;
  cached_input_tokens: number;
  reasoning_tokens: number;
  total_tokens: number;
  billing_units: {
  unit: string;
  quantity: number;
  attributes: Record<string, unknown>;
}[];
  raw_usage: Record<string, unknown>;
  cost_micros?: number;
  price_catalog_revision?: string;
  occurred_at: string;
};

export type ContractTaskCard = {
  schema_version: "1.1";
  card_id: string;
  revision: number;
  task_id: string;
  stage_id: string;
  instance_id: string;
  agent_type: "image" | "ppt";
  objective: string;
  instructions: string[];
  input_assets: {
  asset_id: string;
  manifest_relpath: string;
}[];
  expected_deliveries: ({
  kind: "image" | "presentation" | "document" | "archive" | "other";
  role: string;
  required: boolean;
  accepted_mime_types: string[];
})[];
  parameters: Record<string, unknown>;
  retry_group_id?: string;
  created_at: string;
} & ({
  agent_type?: "image";
  parameters?: {
  aspect_ratio?: string;
  variants?: number;
  usage_context?: string;
  category_id?: string;
  category_version?: string;
};
} | {
  agent_type?: "ppt";
  parameters?: {
  slide_count?: number;
  planned_asset_role?: string;
};
});
